version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: tcc-agon-postgres
    environment:
      POSTGRES_DB: agon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - tcc_postgres_data:/var/lib/postgresql/data

volumes:
  tcc_postgres_data:
