package com.agon.tcc.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum Formato {
	
	PONTOS_CORRIDOS(1, "PONTOS_CORRIDOS"),
	ELIMINATORIA_SIMPLES(2, "ELIMINATORIA_SIMPLES"),
	ELIMINATORIA_DUPLA(3, "ELIMINATORIA_DUPLA"),
	FASE_DE_GRUPOS_COM_ELIMINATORIA_DUPLA(4, "FASE_DE_GRUPOS_COM_ELIMINATORIA_DUPLA"),
	FASE_DE_GRUPOS_COM_ELIMINATORIA_SIMPLES(5, "FASE_DE_GRUPOS_COM_ELIMINATORIA_SIMPLES"),
	PONTOS_CORRIDOS_COM_ELIMINATORIA_SIMPLES(6, "PONTOS_CORRIDOS_COM_ELIMINATORIA_SIMPLES"),
	PONTOS_CORRIDOS_COM_ELIMINATORIA_DUPLA(7, "PONTOS_CORRIDOS_COM_ELIMINATORIA_DUPLA");
	
	private Integer id;
	private String descricao;
	
}
