package com.agon.tcc.model;

public enum Formato {
	
	PONTOS_CORRIDOS,
	ELIMINATORIA_SIMPLES,
	ELIMINATORIA_DUPLA,
	FASE_DE_GRUPOS_COM_ELIMINATORIA_DUPLA,
	FASE_DE_GRUPOS_COM_ELIMINATORIA_SIMPLES,
	PONTOS_CORRIDOS_COM_ELIMINATORIA_SIMPLES,
	PONTOS_CORRIDOS_COM_ELIMINATORIA_DUPLA;

}
